cg_caged.wad
cg_hl.wad
entity.wad
gfx/env/blackbk.tga
gfx/env/blackdn.tga
gfx/env/blackft.tga
gfx/env/blacklf.tga
gfx/env/blackrt.tga
gfx/env/blackup.tga
models/caged/can2.mdl
models/caged/cg_bulb01.mdl
models/caged/cg_flare01.mdl
models/caged/cg_flare02.mdl
models/caged/cg_flare03.mdl
models/caged/cg_flare04.mdl
models/caged/cg_spkrwire_d_01.mdl
models/caged/cg_wires01.mdl
sound/ambience/wind2.wav
sound/buttons/bell1.wav
sound/caged/ambience/cg_achtext01.wav
sound/caged/ambience/cg_alarmbells01.wav
sound/caged/ambience/cg_amb01.wav
sound/caged/ambience/cg_amb04.wav
sound/caged/ambience/cg_amb08.wav
sound/caged/ambience/cg_amb_w_01.wav
sound/caged/ambience/cg_fridge01.wav
sound/caged/ambience/cg_woosh1.wav
sound/caged/barney/bar_step1.wav
sound/caged/barney/bar_step3.wav
sound/caged/music/Caged04.mp3
sound/caged/music/Caged07.mp3
sound/caged/music/Caged08.mp3
sprites/blast.spr
sprites/caged/cg_nuke01.spr
sprites/caged/cg_splash01.spr
sprites/caged/cg_vertflare01.spr
sprites/glow01.spr
sprites/xsmoke1.spr
